package inha.tnt.hbc.domain.message.entity;

public enum AnimationTypes {
	PARTY_POPPER_TYPE1,
	PARTY_POPPER_TYPE2,
	PARTY_POPPER_TYPE3,
	PARTY_POPPER_TYPE4,
	PARTY_POPPER_TYPE5,
	PARTY_POPPER_TYPE6,
	PARTY_POPPER_TYPE7,
	PARTY_POPPER_TYPE8,
	PARTY_POPPER_TYPE9,
}
