package inha.tnt.hbc.domain.message.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum MessageDecorationTypes {
	DOLL_TYPE1("DOLL"),
	DOLL_TYPE2("DOLL"),
	DOLL_TYPE3("DOLL"),
	DOLL_TYPE4("DOLL"),
	DOLL_TYPE5("DOLL"),
	DOLL_TYPE6("DOLL"),
	DOLL_TYPE7("DOLL"),
	DOLL_TYPE8("DOLL"),
	DOLL_TYPE9("DOLL"),

	PIC_TYPE1("PIC"),

	FOOD_TYPE1("FOOD"),
	FOOD_TYPE2("FOOD"),
	FOOD_TYPE3("FOOD"),
	FOOD_TYPE4("FOOD"),
	FOOD_TYPE5("FOOD"),
	FOOD_TYPE6("FOOD"),
	FOOD_TYPE7("FOOD"),
	FOOD_TYPE8("FOOD"),
	FOOD_TYPE9("FOOD"),
	FOOD_TYPE10("FOOD"),

	GIFT_TYPE1("GIFT"),
	GIFT_TYPE2("GIFT"),
	GIFT_TYPE3("GIFT"),
	GIFT_TYPE4("GIFT"),
	GIFT_TYPE5("GIFT"),
	GIFT_TYPE6("GIFT"),
	GIFT_TYPE7("GIFT"),
	GIFT_TYPE8("GIFT"),
	GIFT_TYPE9("GIFT"),
	GIFT_TYPE10("GIFT"),

	DRINK_TYPE1("DRINK"),
	DRINK_TYPE2("DRINK"),
	DRINK_TYPE3("DRINK"),
	DRINK_TYPE4("DRINK"),
	DRINK_TYPE5("DRINK"),
	DRINK_TYPE6("DRINK"),
	DRINK_TYPE7("DRINK"),
	DRINK_TYPE8("DRINK"),
	DRINK_TYPE9("DRINK"),
	DRINK_TYPE10("DRINK"),
	DRINK_TYPE11("DRINK"),
	DRINK_TYPE12("DRINK"),
	DRINK_TYPE13("DRINK"),
	DRINK_TYPE14("DRINK"),
	DRINK_TYPE15("DRINK"),
	DRINK_TYPE16("DRINK"),
	DRINK_TYPE17("DRINK"),
	DRINK_TYPE18("DRINK"),
	DRINK_TYPE19("DRINK"),
	DRINK_TYPE20("DRINK"),
	;

	private final String category;
}
